spring.application.name=MaShakti_LoanService
# Cloud MySQL Database Configuration
spring.datasource.url=jdbc:mysql://mysql-dc086a8-mashakti-loan.e.aivencloud.com:25107/defaultdb?ssl-mode=REQUIRED
spring.datasource.username=avnadmin
spring.datasource.password=${DB_PASSWORD}


# Hibernate properties (Jo table apne aap cloud database me banaye)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect